---
- hosts: Jenkinclient
  gather_facts: false
  vars_files:
    - envpd.yaml
  tasks:
  - name: Copy the file from server machine to client machine
    copy:
       src: "{{ pdsetup.serversoft }}"
       dest: "{{ pdsetup.clientsoft }}"
  - name: Unzipping Ping Directory
    shell: cd {{ pdsetup.clientsoft }} ; unzip {{ pdsetup.zipfile }} ; 

  - name: Changing the Ping Directory folder name
    shell: mv {{ pdsetup.clientsoft }}/{{ pdsetup.folder }} {{ pdsetup.clientsoft }}/{{ pdsetup.pd1 }} ;
  
  - name: Moving the Ping Directory
    shell: mv {{ pdsetup.clientsoft }}/{{ pdsetup.pd1 }} {{ pdsetup.clientprog }}/ ;
    become: yes
    become_method: sudo 

  - name: Setup the PingDirectory 1
    shell: cd {{ pdsetup.clientprog }}/{{ pdsetup.pd1 }}/ ; ./setup --acceptLicense --no-prompt --script-friendly    --localHostName {{ rep.pd1.hostname }}    --ldapPort {{ rep.pd1.ldapport }}    --ldapsPort {{ rep.pd1.ldapsport }}    --httpsPort {{ rep.pd1.httpsport }}    --rootUserDN {{ rep.pd1.userdn }}    --rootUserPassword {{ rep.pd1.password }}    --maxHeapSize 512m    --enableStartTLS    --generateSelfSignedCertificate    --baseDN {{ rep.pd1.basedn }}    --addBaseEntry ;

  - name: Restart the PingDirectory 1
    shell: cd {{ pdsetup.clientprog }}/{{ pdsetup.pd1 }}/bin ; nohup ./stop-ds -R &
  - pause: seconds=30
...
